name: 'Dockerize'

on:
  workflow_dispatch:

inputs:
  registry:
    required: true
    default: 'ghcr.io'

  image-ref:
    required: true
    default: null

  github-token:
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.8.0

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3.3.0
      with:
        registry: ${{ inputs.registry }}
        username: ${{ github.actor }}
        password: ${{ inputs.github-token }}

    - name: Build and push Docker image
      id: build-and-push
      uses: docker/build-push-action@v6.13.0
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        provenance: false
        platforms: "linux/amd64"
        tags: ${{ inputs.image-ref }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
